### ISSUE TITLE
Keep original file dates and times after transcoding - does not work on windows?

### ISSUE THREAD

**Issue by Mcavity5** [HaveAGitGat/Tdarr_Plugins#349]
It seems the "keep the date" plugin is not working on windows nodes. 
I and running direct on my windows 10 system. 
I receive the error message " 2022-10-30T13:40:00.268Z Could not find file using API using x.x.x.x"
I have tried configuring with the ip, and with 127.0.0.1 [both should be valid as the tdarr server and node run on the same system]
The files are stored on a remote storage server. 
I'm happy to offer any help I can to help resolve this.

**Comment by Mcavity5** [comment]
minor update. I moved the "server" node to a Linux box while keeping the transcode node on the windows box. It looks like the "keep the date" plugin works this way. 


2022-11-01T13:42:37.321Z Post-processing - Keep original file dates and times after transcoding
24 2022-11-01T13:42:37.321Z File timestamps updated or match original file
25 2022-11-01T13:42:37.321Z
26 2022-11-01T13:42:37.322Z Y6HmBtKHJHr:Removing original item from database
27 2022-11-01T13:42:37.322Z Y6HmBtKHJHr:Adding new file to database
28 2022-11-01T13:42:37.322Z Y6HmBtKHJHr:Updating size stats

**Comment by HaveAGitGat** [comment]
Bit of trial and error as `touch.sync` does not seem to work on windows but this fix should be working:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/478

**Comment by dougbenham** [comment]
The fix didn't work because windows machines still fail on `const touch = require('touch');`
