### ISSUE TITLE
ffmpegCommand10BitVideo doesn't work with ffmpegCommandSetVideoEncoder(av1)

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr_Plugins#672]
https://github.com/HaveAGitGat/Tdarr/issues/1032

**Describe the bug**
When using this flow my ffmpeg commands will fail if the original file is 10 bit, the reason is that ffmpegCommand10BitVideo will inject `-profile:v:0 main10` but this is not supported with `libsvtav1`
![image](https://github.com/HaveAGitGat/Tdarr/assets/24446198/737eb5da-77a1-4cad-a212-f4eddf99e201)

**To Reproduce**
Use ffmpegCommand10BitVideo with ffmpegCommandSetVideoEncoder in av1 mode

**Expected behavior**
From [the documentation](https://trac.ffmpeg.org/wiki/Encode/AV1), set 10 bit should add something like `-pix_fmt yuv420p10le`

I'm currently using tdarr node on Windows 11 with ffmpeg version 7.0.1-full_build

**Comment by HaveAGitGat** [comment]
@Maxmystere should be fixed with: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/676/files

**Comment by Maxmystere** [comment]
Seeing your change does the mean the SetEncoder has to always be called before Set10Bit ?

**Comment by taltamir** [comment]
> @Maxmystere should be fixed with: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/676/files

I looked at the code linked and it very clearly does not fix it.
```
if (stream.codec_type === 'video') {
            stream.outputArgs.push('-profile:v:{outputTypeIndex}', 'main10');
            if (stream.outputArgs.some(function (row) { return row.includes('qsv'); }) && os_1.default.platform() !== 'win32') {
                stream.outputArgs.push('-vf', 'scale_qsv=format=p010le');
            }
            else if (stream.outputArgs.some(function (row) { return row.includes('libsvtav1'); })) {
                stream.outputArgs.push('-pix_fmt:v:{outputTypeIndex}', 'yuv420p10le');
            }
```
you have in order:
1. if video add main10 profile:v:0
2. if not windows add `scale_qsv=format=p010le`
3. else if libsvtav1 add `yuv420p10le`

where 3 is new.
the main problem is number 1. which is always added because it is a video. and causes ffmpeg to error out when trying to encode libsvtav1.

number 2 gets auto corrected to number 3. but now you add a 2nd copy of it for number 3.

as a result, this will produce a
`ffmpeg input.mkv -c:v libsvtav1 main10 profile:v:0 -pix_fmt:v:0 p010le -pix_fmt:v:0 yuv420p10le`
where it should be doing
`ffmpeg input.mkv -c:v libsvtav1 -pix_fmt:v:0 yuv420p10le`

**Comment by taltamir** [comment]
Also, to be honest this 10 bit command should be integrated into `ffmpeg command: set video encoder`
where each encoder should have a dropdown with whatever valid color bit depths are available for it.
for av1 it should be 8bit, 10bit, or 12bit.

**Comment by Kitt3120** [comment]
Hey, I am running into the same problem. Any updates on this? :)

**Comment by HaveAGitGat** [comment]
Fixed by https://github.com/HaveAGitGat/Tdarr_Plugins/pull/676
